version: 2
updates:
  # Node.js (npm)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "eslint"
        versions: ["8.x"]
  # Python (pip)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  # Composer (PHP)
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
  # Ruby (bundler)
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
  # Go
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
  # Java (Maven)
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
  # Rust (Cargo)
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
  # NuGet (.NET)
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
  # Elixir (mix)
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
  # Swift (CocoaPods)
  - package-ecosystem: "cocoapods"
    directory: "/"
    schedule:
      interval: "weekly"
  # Gradle (Java)
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
  # Pub (Dart/Flutter)
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
  # Hex (Erlang/Elixir)
  - package-ecosystem: "hex"
    directory: "/"
    schedule:
      interval: "weekly"

# Optional: Enable versioning strategy and automerge
  # You can uncomment these lines if you want:
  # versioning-strategy: increase
  # automerge: true
